import {User} from './githubModels'

let u1:User ={
  "login": "stomaras",
  "id": 22882822,
  "node_id": "MDQ6VXNlcjIyODgyODIy",
  "avatar_url": "https://avatars.githubusercontent.com/u/22882822?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/stomaras",
  "html_url": "https://github.com/stomaras",
  "followers_url": "https://api.github.com/users/stomaras/followers",
  "following_url": "https://api.github.com/users/stomaras/following{/other_user}",
  "gists_url": "https://api.github.com/users/stomaras/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/stomaras/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/stomaras/subscriptions",
  "organizations_url": "https://api.github.com/users/stomaras/orgs",
  "repos_url": "https://api.github.com/users/stomaras/repos",
  "events_url": "https://api.github.com/users/stomaras/events{/privacy}",
  "received_events_url": "https://api.github.com/users/stomaras/received_events",
  "type": "User",
  "site_admin": false,
  "name": "stomaras",
  "company": null,
  "blog": "https://www.linkedin.com/in/spyros-tomaras/",
  "location": "Athens, Greece",
  "email": null,
  "hireable": null,
  "bio": "Aueb department of management science and technology @aueb\r\n\r\n\r\nMsc in Advanced Software Technologies And Artificial Intelligence.\r\nUniversity of Peiraus\r\n",
  "twitter_username": null,
  "public_repos": 69,
  "public_gists": 0,
  "followers": 20,
  "following": 34,
  "created_at": "2016-10-17T08:23:29Z",
  "updated_at": "2022-07-14T08:19:54Z"
}